# Generated by Django 2.2.12 on 2021-12-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0003_task_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deleted',
        ),
    ]
